"""Keyword definitions for intent detection."""



FACT_QA_KEYWORDS: set[str] = {
    # Financial metrics
    "revenue",
    "profit",
    "earnings",
    "income",
    "sales",
    "margin",
    "ebitda",
    "roce",
    "roe",
    "roa",
    "eps",
    "pe ratio",
    "dividend",
    "yield",
    "cash flow",
    "debt",
    "assets",
    "liabilities",
    "equity",
    "valuation",
    "market cap",
    "enterprise value",
    # Temporal indicators
    "when",
    "date",
    "year",
    "quarter",
    "q1",
    "q2",
    "q3",
    "q4",
    "annual",
    "monthly",
    "timeline",
    "history",
    "historical",
    "past",
    "previous",
    "recent",
    "latest",
    # Question words for facts
    "what is",
    "what was",
    "how much",
    "how many",
    "which",
    "who is",
    "where",
    # Company information
    "founded",
    "established",
    "headquarters",
    "ceo",
    "founder",
    "employees",
    "industry",
    "sector",
    "products",
    "services",
    "market share",
    "ranking",
    # Performance indicators
    "performance",
    "growth",
    "increase",
    "decrease",
    "change",
    "trend",
    "forecast",
    "guidance",
    "outlook",
    "projection",
    "estimate",
    "results",
    "report",
    # Chinese keywords
    "营收",
    "利润",
    "盈利",
    "收入",
    "销售额",
    "毛利率",
    "净利率",
    "资产收益率",
    "股本回报率",
    "每股收益",
    "市盈率",
    "股息",
    "现金流",
    "负债",
    "资产",
    "市值",
    "什么是",
    "多少",
    "哪个",
    "谁是",
    "在哪里",
    "成立",
    "总部",
    "行业",
    "产品",
}

RELATIONSHIP_KEYWORDS: set[str] = {
    # Relationship indicators
    "relationship",
    "relation",
    "connection",
    "between",
    "among",
    "with",
    "partner",
    "partners",
    "partnership",
    "competitor",
    "competitors",
    "competition",
    "rival",
    "versus",
    "vs",
    "supplier",
    "customer",
    "client",
    "vendor",
    "distributor",
    "investor",
    # Comparative terms
    "compare",
    "comparison",
    "compared to",
    "relative to",
    "against",
    "difference",
    "similar",
    "similarity",
    "like",
    "unlike",
    "contrast",
    "correlation",
    # Network terms
    "network",
    "ecosystem",
    "chain",
    "linked",
    "connected",
    "associated",
    "affiliated",
    "subsidiary",
    "parent",
    "holding",
    "owned by",
    "owns",
    # Collaborative terms
    "collaborate",
    "collaboration",
    "joint venture",
    "merger",
    "acquisition",
    "alliance",
    "cooperation",
    "agreement",
    "contract",
    "deal",
    "transaction",
    # Dependency terms
    "depend",
    "dependency",
    "relies on",
    "based on",
    "influenced by",
    "affects",
    "impact",
    "influence",
    "caused by",
    "leads to",
    "results in",
    # Chinese keywords
    "关系",
    "关联",
    "联系",
    "之间",
    "合作",
    "竞争",
    "对手",
    "供应商",
    "客户",
    "比较",
    "对比",
    "相比",
    "相似",
    "类似",
    "不同",
    "网络",
    "生态",
    "链条",
    "子公司",
    "母公司",
    "收购",
    "并购",
    "合资",
    "联盟",
    "影响",
    "依赖",
    "相关",
    "竞品",
    "上下游",
}


def normalize_keywords() -> dict[str, set[str]]:
    """Normalize keywords to lowercase for case-insensitive matching."""
    return {
        "fact_qa": {kw.lower() for kw in FACT_QA_KEYWORDS},
        "relationship": {kw.lower() for kw in RELATIONSHIP_KEYWORDS},
    }


def get_all_keywords() -> set[str]:
    """Get all keywords from both categories."""
    return FACT_QA_KEYWORDS.union(RELATIONSHIP_KEYWORDS)
