ner:
  system: |
    您的任务是从给定的中文段落中，精准地提取出所有具有重要意义的命名实体，并为每个实体分配一个预定义的类型标签。
    请以JSON格式返回一个对象，其中包含一个`named_entities`列表。列表中的每个元素都是一个对象，包含`text`（实体文本）和`type`（实体类型）两个键。

    请从以下预定义类型中为每个实体选择最合适的标签：
    - COMPANY: 公司或集团主体
    - SUBSIDIARY: 明确提及的子公司
    - AFFILIATE: 明确提及的参股或联营公司
    - BUSINESS_SEGMENT: 主要的业务板块或部门
    - CORE_BUSINESS: 对核心业务或商业模式的描述
    - PRODUCT: 具体的产品、服务或品牌名称
    - TECHNOLOGY: 技术、技术领域或关键能力
    - INDUSTRY_APPLICATION: 产品的目标应用领域或行业
    - COMPANY_CODE: 公司代码
  
  examples:
    - user: |
        ## 公司简称
        综艺股份
        
        ## 公司代码
        600770
        
        ## 主营业务
        ### 信息科技板块
        * **子公司南京天悦**：
            * 核心业务：超低功耗数模混合助听器芯片及高端数字语音处理技术的研发，提供芯片+算法全套解决方案
            * 主要产品/服务：HA3950、HA330G、HA601SC、HA631SC芯片
            * 目标应用领域：助听器市场，包括耳背机、耳内机、盒式机等
        * **参股公司神州龙芯**：
            * 核心业务：集成电路设计、研发与销售，布局税控产品、密码产品等领域
            * 主要产品/服务：处理器、主板及系统级产品，芯片设计服务与系统板卡定制服务
            * 目标应用领域：工业控制、能源电力、通讯控制、伺服控制、数据采集等
        * **子公司毅能达**：
            * 核心业务：智能卡及其应用技术、系统集成和手持、自助终端设备的研发、设计、制造、营销与服务
            * 主要产品/服务：磁条卡/条码卡、接触式IC卡、感应式IC卡、复合卡、双界面CPU卡、3D智能卡、RFID卡/电子标签、智能穿戴手表、自助终端设备
            * 目标应用领域：金融社保、交通、教育、公安、金融、电信、商业、公共事业等
        * **子公司掌上明珠**：
            * 核心业务：手机移动游戏开发与运营
            * 主要产品/服务：《明珠三国》、《明珠轩辕》等角色扮演类游戏
            * 目标应用领域：移动游戏市场
        * **子公司江苏综创**：
            * 核心业务：计算机系统集成技术服务
            * 主要产品/服务：计算机硬件设备销售和系统集成技术服务
            * 目标应用领域：信息化建设项目
        
        ### 新能源板块
        * **太阳能电站业务**：
            * 核心业务：太阳能电站的运营、维护及管理
            * 主要产品/服务：集中式、分布式光伏电站
            * 目标应用领域：国内外太阳能电力市场
        * **子公司综艺光伏**：
            * 核心业务：投资并购环保业务，与新能源业务协同发展
            * 主要产品/服务：活性碳纤维材料、VOCs吸附溶剂回收设备、环保装备制造
            * 目标应用领域：溶剂回收、民用净水、空气净化等环保领域
        
        ### 股权投资板块
        * **子公司江苏高投**：
            * 核心业务：股权投资
            * 主要产品/服务：向科技含量高、成长性好的创业企业提供股权资本
            * 目标应用领域：科技、成长性企业
        
        ### 整体业务总结
        * 公司业务多元化，涵盖信息科技、新能源和股权投资三大板块。信息科技板块以芯片设计、智能卡和手游为核心，新能源板块专注于太阳能电站运营和环保业务，股权投资板块则聚焦于高成长性科技企业。各业务板块相互协同，形成产业链延伸和多元化发展格局。
        
        ## 关键词
        芯片设计,智能卡,手游,太阳能电站,环保设备,股权投资
      
      assistant: |
        {"named_entities": [
          {"text": "综艺股份", "type": "COMPANY"},
          {"text": "600770", "type": "COMPANY_CODE"},
          {"text": "信息科技板块", "type": "BUSINESS_SEGMENT"},
          {"text": "南京天悦", "type": "SUBSIDIARY"},
          {"text": "超低功耗数模混合助听器芯片", "type": "TECHNOLOGY"},
          {"text": "高端数字语音处理技术", "type": "TECHNOLOGY"},
          {"text": "HA3950", "type": "PRODUCT"},
          {"text": "HA330G", "type": "PRODUCT"},
          {"text": "HA601SC", "type": "PRODUCT"},
          {"text": "HA631SC", "type": "PRODUCT"},
          {"text": "助听器市场", "type": "INDUSTRY_APPLICATION"},
          {"text": "神州龙芯", "type": "AFFILIATE"},
          {"text": "集成电路设计", "type": "CORE_BUSINESS"},
          {"text": "税控产品", "type": "PRODUCT"},
          {"text": "密码产品", "type": "PRODUCT"},
          {"text": "处理器", "type": "PRODUCT"},
          {"text": "主板", "type": "PRODUCT"},
          {"text": "毅能达", "type": "SUBSIDIARY"},
          {"text": "智能卡", "type": "TECHNOLOGY"},
          {"text": "掌上明珠", "type": "SUBSIDIARY"},
          {"text": "手机移动游戏开发与运营", "type": "CORE_BUSINESS"},
          {"text": "《明珠三国》", "type": "PRODUCT"},
          {"text": "《明珠轩辕》", "type": "PRODUCT"},
          {"text": "江苏综创", "type": "SUBSIDIARY"},
          {"text": "计算机系统集成技术服务", "type": "CORE_BUSINESS"},
          {"text": "新能源板块", "type": "BUSINESS_SEGMENT"},
          {"text": "太阳能电站业务", "type": "CORE_BUSINESS"},
          {"text": "集中式、分布式光伏电站", "type": "PRODUCT"},
          {"text": "综艺光伏", "type": "SUBSIDIARY"},
          {"text": "投资并购环保业务", "type": "CORE_BUSINESS"},
          {"text": "活性碳纤维材料", "type": "PRODUCT"},
          {"text": "VOCs吸附溶剂回收设备", "type": "PRODUCT"},
          {"text": "股权投资板块", "type": "BUSINESS_SEGMENT"},
          {"text": "江苏高投", "type": "SUBSIDIARY"},
          {"text": "股权投资", "type": "CORE_BUSINESS"}
        ]}
  
  template: "${passage}"